builds:
  - main: main.go
    binary: aws_tags_exporter
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tar.gz
  files:
    - README.md
    - LICENSE

dist: _output
